language: node_js

node_js: '9'

cache: yarn

install:
  - sudo apt-get --yes install snapd
  - sudo snap install hugo

before_script:
  - yarn install

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN
  on:
    branch: master