language: node_js

node_js: '6'

cache: yarn

# Clean and don't fail
install:
  - yarn install

# Build the website
script:
  - npm run build

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master