language: node_js

node_js: '9'

cache: yarn

before_script:
  - yarn install

script:
  - gulp sass
  - gulp js
  - gulp fonts
  - gulp images
  - binaries/hugo

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN
  on:
    branch: master