language: node_js

node_js: '9'

cache: yarn

install: go get -v github.com/spf13/hugo

before_script:
  - npm install -g gulp
  - yarn install

# Build the website
script:
  - npm run build

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master