language: node_js

node_js: '9'

cache: yarn

install:
  - go get -v github.com/spf13/hugo

before_script:
  - npm install -g gulp
  - yarn install

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN
  on:
    branch: master